In [65]:
#1
a = int(input("Nhap vao gia tri a: "))
b = int(input("Nhap vao gia tri b: "))
print(a+b)
print(a-b)
print(a*b)
print(a/b)

Nhap vao gia tri a: 2
Nhap vao gia tri b: 1
3
1
2
2.0


In [66]:
#2
my_string = "Hello World"
subString_to_find = "llo"
if subString_to_find in my_string:
  print(subString_to_find)

llo


In [67]:
#3
my_string = " Hello World "
my_string = my_string.strip()
print(my_string)
my_string = my_string.replace("H","J")
print(my_string)

Hello World
Jello World


In [68]:
#4
my_string = "Hello World"
a = 3
b = 2
if(a>b):
  print(my_string)

Hello World


In [69]:
#5
a = int(input("Nhap vao gia tri a: "))
b = int(input("Nhap vao gia tri b: "))
if a == b:
  print("Yes")
else :
  print("No")

Nhap vao gia tri a: 2
Nhap vao gia tri b: 3
No


In [70]:
#6
a = int(input("Nhap vao gia tri a: "))
b = int(input("Nhap vao gia tri b: "))
if a == b:
  print(1)
elif a > b:
  print(2)
else:
  print(3)

Nhap vao gia tri a: 4
Nhap vao gia tri b: 1
2


In [71]:
#7
a = int(input("Nhap vao gia tri a: "))
b = int(input("Nhap vao gia tri b: "))
c = int(input("Nhap vao gia tri c: "))
d = int(input("Nhap vao gia tri d: "))
if (a==b) and (c==d):
  print("Hello World!")
else:
  print("No")

Nhap vao gia tri a: 2
Nhap vao gia tri b: 3
Nhap vao gia tri c: 4
Nhap vao gia tri d: 5
No


In [72]:
#8
a = int(input("Nhap vao gia tri a: "))
b = int(input("Nhap vao gia tri b: "))
c = int(input("Nhap vao gia tri c: "))
d = int(input("Nhap vao gia tri d: "))

if (a==b) or (c==d):
  print("Hello World!")
else:
  print("No")

Nhap vao gia tri a: 1
Nhap vao gia tri b: 2
Nhap vao gia tri c: 3
Nhap vao gia tri d: 4
No


In [73]:
#9
a = 2; b = 3
print('Yes') if (a>b) else print('No')

No


In [74]:
#10
a = int(input("Nhap vao gia tri a: "))
b = int(input("Nhap vao gia tri b: "))
print("A") if a > b else print("=") if a==b else print("B")

Nhap vao gia tri a: 1
Nhap vao gia tri b: 2
B


In [75]:
#11
import numpy as np
arr1 = np.arange(10)
arr2 = []
for i in arr1:
  if i % 2 == 0:
    arr2.append(i)
arr2 = np.array(arr2)
print(arr2)
print(arr1)

[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [76]:
#12
import numpy as np
arr = np.arange(1000)
sum = 0
for i in arr:
  if i % 3 == 0 or i % 5 == 0:
    sum = sum + i
print(sum)

233168


In [77]:
#13
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([1,3,5,7])
arr3 = []
min = len(arr2) if len(arr1)>len(arr2) else len(arr1)
arr3 = arr1 if len(arr1)>len(arr2) else arr2
for i in range(min):
  arr3[i] = arr1[i] + arr2[i]
print(arr3)

[ 2  5  8 11  5  6]


In [78]:
#14
#a
import numpy as np
m = int(input("Nhap vao so hang: "))
n = int(input("Nhap vao so cot: "))
arr1 = np.random.randn(m,n)

Nhap vao so hang: 3
Nhap vao so cot: 2


In [79]:
#14
#b
import numpy as np
m = int(input("Nhap vao so hang: "))
n = int(input("Nhap vao so cot: "))
arr1 = np.random.randn(m,n)
k = int(input(f"Nhap vao dong k (Tu 0 den {m-1}): "))
if 0 <= k < m:
    dong_k = arr1[k, :]
    print(f"Dong thu {k} la: \n{dong_k}")
else:
    print(f"Loi: Chi so dong phai nam trong khoang tu 0 den {m-1}!")

Nhap vao so hang: 1
Nhap vao so cot: 3
Nhap vao dong k (Tu 0 den 0): 0
Dong thu 0 la: 
[ 0.84974219 -0.23775205  1.43298841]


In [80]:
#14
#c
import numpy as np
m = int(input("Nhap vao so hang: "))
n = int(input("Nhap vao so cot: "))
arr1 = np.random.randn(m,n)
k = int(input(f"Nhap vao cot k (Tu 0 den {m-1}):"))
dong_k = arr1[:, k]
print(f"Cot thứ {k} la: \n{dong_k}")

Nhap vao so hang: 1
Nhap vao so cot: 2
Nhap vao cot k (Tu 0 den 0):0
Cot thứ 0 la: 
[-0.45131984]


In [81]:
#14
#d
import numpy as np
m = int(input("Nhap so hang m: "))
n = int(input("Nhap so cot n: "))
arr1 = np.random.randint(0, 51, size=(m, n))
print("Mang a:")
print(arr1)
tong_cac_dong = np.sum(arr1, axis=1)
vi_tri_max = np.argmax(tong_cac_dong)
print(f"Dong co tong lon nhat la dong: {vi_tri_max}")
print(f"Gia tri tong do la: {tong_cac_dong[vi_tri_max]}")


Nhap so hang m: 2
Nhap so cot n: 4
Mang a:
[[ 1 32  7 10]
 [13  1 29 41]]
Dong co tong lon nhat la dong: 1
Gia tri tong do la: 84
